# Generated by Django 5.0.6 on 2024-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('math_solver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='FAILED', max_length=64)),
                ('action', models.CharField(blank=True, max_length=64)),
                ('content', models.JSONField()),
                ('errors', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='status',
            field=models.CharField(blank=True, default='CREATED', max_length=64),
        ),
        migrations.AlterField(
            model_name='solution',
            name='status',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
